name: Deploy to GCS

on:
push:
branches:
- main

jobs:
deploy:
runs-on: ubuntu-latest

```
steps:
  - uses: actions/checkout@v4

  - uses: google-github-actions/auth@v2
    with:
      credentials_json: ${{ secrets.GCP_SA_KEY }}

  - uses: google-github-actions/setup-gcloud@v2

  - run: gsutil -m cp -r . gs://cloud-course-laxmi-21623
```
